language: node_js
node_js:
    - "node"
env:
    global:
        - DISPLAY=:100
        - TEST_FIREFOX_BIN=/usr/bin/firefox
install:
    - npm install
    - npm ls; true
jobs:
    include:
        - stage: test
          env: TEST_SUITE=lint,unit,integration
          sudo: required
          dist: trusty
          before_install:
              - lsb_release -a
              - sudo add-apt-repository -y ppa:ubuntu-mozilla-daily/firefox-aurora
              - sudo apt-get update
              - sudo apt-get install -y firefox
              - '"$TEST_FIREFOX_BIN" --version'
          script:
              - npm run lint
              - npm run test:unit:coveralls
